import LocalizedStrings from 'react-native-localization';
let Strings = new LocalizedStrings({
      "en-US": {
            login: 'Sign In',
            email: 'Email',
            password: 'Password',
            verify: "Verify",
            forgotPassword: "Forgot Password",
            varifyPassword: "Varify OTP",
            changePassword: "Change Password",
            confirmPassword: "Confirm Password",
            orText: "---- Or Sign In with ----",
            submit: "Submit",
            socialText: "Sign up with social networks",
            googleLogin: "Sign in with google",
            fbLogin: "Login with facebook",
            dontHaveAccount: "Don't have an account? ",
            signInCancelled: "Sign In Cancelled",
            inProgress: 'Progress',
            serviceNotAvailable: "service Not Available",
            signUp: "Sign Up ",
            blankEmailError: 'Please enter email address',
            validEmailError: 'Please enter valid email address',
            enterPasswordError: 'Please enter password',
            validPasswordError: 'Please enter minimum six digits',
            wrong: 'Something went wrong here.',
            noSpace: 'No Space Allowed',
            requiredField: 'This field is required',
            maxLimit: 'please enter at least six character',

            myOrders: "My Orders",
            myActiveOrders: "My Active Orders",
            seeAllOrders: "See All Orders",
            orderId: "Order Id",
            status: "Status",
            services: "Services",
            chatWithUs: "Chat with us",
            members: "Members",

            allAttachments: "All Attachments",
            addedeOn: "Added On",
            order: "Order Id",
            payment: "Payment",
            paymentDetail: "Payment Detail",
            totalAmount: "Total Amount",
            chatWindow: "Chat Window",

            updateProfile: "Update Profile",

            usernameProp: 'UserName',
            username: 'User Name',
            mobile: "Mobile",
            mobileNumber: "Mobile Number",
            emailAddress: "Email Address",
            state: "State",
            city: "City",
            zipcode: "Zipcode",
            update: "Update",
            name:"Name",
            contact:"Contact",
             countryCode :"Country Code",


            userProp: 'firstname',
            emailProp: 'email',
            mobileProp: 'contact',
            stateProp: 'state',
            cityProp: 'city',
            zipcodeProp: 'postalcode',
            attachments: "Attachments",
            notifications: "Notifications",
            more: "More",
            speed:"Speed",
            Edit:"Edit",
            personalInfo: "Personal Information",
            category:'Selcect Category',
            subcategory:'Selcect SubCategory',
            Profile:"Profile",
            SourceSansProBlack:'SourceSansPro-Black',
            SourceSansProLight: 'SourceSansPro-Light',
            SourceSansProBold:'SourceSansPro-Bold',
            SourceSansProBlackItalic:'SourceSansPro-BlackItalic',
            SourceSansProRegular:'SourceSansPro-Regular',
            SourceSansProExtraLight:'SourceSansPro-ExtraLight',
            SegoeUi:'SEGOEUI'

      },
})
export default Strings;
